name: lint
on:
  - push
  - pull_request
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - uses: pnpm/action-setup@fe02b34f77f8bc703788d5817da081398fad5dd2 # v4.0.0
        name: Install pnpm
        with:
          run_install: false

      - name: Setup node
        uses: actions/setup-node@1e60f620b9541d16bece96c5465dc8ee9832be0b # v.4.0.3
        with:
          node-version-file: .node-version
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Cache Turbo
        uses: actions/cache@0c45773b623bea8c8e75f6c82b208c3cf94ea4f9 # v.4.0.2
        with:
          path: .turbo
          key: turbo-${{ github.job }}-${{ github.ref_name }}-${{ github.sha }}
          restore-keys: |
            turbo-${{ github.job }}-${{ github.ref_name }}-

      - name: Run lint
        run: pnpm run lint
